### ISSUE TITLE
Repository organisation

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp_benchmark#8]
Hi, the list of dates becomes long. I have two proposal about this:
- organize the folder in a hierarchy `year/month/day` instead of a flat hierarchy `year-month-day`.
- why is the history of benchmarks not stored in the git history, meaning that, to see the benchmarks of a given moment, one would have to checkout the appropriate commit.

As I see no problem for the second point, it is the one I would favor although it requires a bit more work to achieve. The first point is very easy to achieve.

**Comment by nim65s** [comment]
with git [worktree](https://git-scm.com/docs/git-worktree) it could be pretty easy to access one benchmark or another, I guess.

**Comment by florent-lamiraux** [comment]
Solved by https://github.com/humanoid-path-planner/hpp_benchmark/pull/21.
